### ISSUE TITLE
Style: Indent level in switch blocks

### ISSUE THREAD

**Issue by PikalaxALT** [pret/pokeheartgold#227]
Variant A: Case labels flush with the switch statement. This is the standard in [pret/pokeruby](/pret/pokeruby) etc.
```c
switch (state) {
case 0:
    // ...
case 1:
    // ...
}
```

Variant B: Case labels indented by 1.
```c
switch (state) {
    case 0:
        // ...
    case 1:
        // ...
}
```

**Comment by adrienntindall** [comment]
Variant A is better due to how many nested switch statements are in the code. The alternative would be to have the deepest indent in large essential functions be 3-4 indents deeper than they would have been sticking with variant A, which makes the code less readable. Then for consistency we should keep the rest of the code on the same style.

**Comment by red031000** [comment]
I have made several PRs converting style A into style B, which have been approved and merged, and during original style guide discussions, we did decided on style B, so imo style B is better, plus, I prefer it because I personally find it much easier to read

**Comment by AsparagusEduardo** [comment]
I prefer style B.

**Comment by mid-kid** [comment]
Style A reinforces the fact that the case labels have no scoping significance and have about the same effect as a `goto` statement. It's also wasteful to add an indent level when unnecessary.

**Comment by luckytyphlosion** [comment]
I abstain from this discussion.

**Comment by luckytyphlosion** [comment]
There is actually a third variant C: case labels indented by 1, but case contents not indented.
```
switch (state) {
    case 0:
    // ...
    case 1:
    // ...
}
```

I only mention this because this is the default in Notepad++. With that, I want to mention that editors are inconsistent as to which style they automatically indent to:

| Editor | Default behaviour | Toggleable
|------|-------------|---------
| Notepad++ | Variant C | Unknown ([Discussion 1](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/296#issuecomment-135769787), [Discussion 2](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/821))
| Eclipse (yes this isn't C I know) | Variant A | Yes, see image below
| Visual Studio Code | Variant B | Yes? ([Issue which proves its existence in vscode-cpptools extension](https://github.com/microsoft/vscode-cpptools/issues/6806))

For eclispe:
![image](https://github.com/pret/pokeheartgold/assets/10688458/057d435a-a910-4d68-80a9-3f71067da07b)

**Comment by red031000** [comment]
> There is actually a third variant C: case labels indented by 1, but case contents not indented.
> 
> ```
> switch (state) {
>     case 0:
>     // ...
>     case 1:
>     // ...
> }
> ```
> 
> I only mention this because this is the default in Notepad++. With that, I want to mention that editors are inconsistent as to which style they automatically indent to:
> 
> Editor	Default behaviour	Toggleable
> Notepad++	Variant C	Unknown ([Discussion 1](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/296#issuecomment-135769787), [Discussion 2](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/821))
> Eclipse (yes this isn't C I know)	Variant A	Yes, see image below
> Visual Studio Code	Variant B	Yes? ([Issue which proves its existence in vscode-cpptools extension](https://github.com/microsoft/vscode-cpptools/issues/6806))
> For eclispe: ![image](https://user-images.githubusercontent.com/10688458/262107869-057d435a-a910-4d68-80a9-3f71067da07b.png)

objectively bad

**Comment by AsparagusEduardo** [comment]
> There is actually a third variant C: case labels indented by 1, but case contents not indented.

It's like the worst of both worlds

**Comment by tgsm** [comment]
I prefer style B.
